### ISSUE TITLE
Aclaración viajes

### ISSUE THREAD

**Issue by lmorillas** [johannague/tutorial_wagtail_final#2]
Puedes aclara la aplicación de viajes? Por qué Viaje es  https://github.com/johannague/tutorial_wagtail_final/blob/3b5b24b3ef0c4221fca32c5cee961d2ed5074f9f/viajes/models.py#L11 y ViajesPage https://github.com/johannague/tutorial_wagtail_final/blob/3b5b24b3ef0c4221fca32c5cee961d2ed5074f9f/viajes/models.py#L33 ?   (models.Model y Page respectivamente)

**Comment by johannague** [comment]
se elimino en la aplicacion viajes (viaje(models.Model), no aportaba nada.
