### ISSUE TITLE
Redirecciones erróneas

### ISSUE THREAD

**Issue by lmorillas** [johannague/tutorial_wagtail_final#3]
No puedes usar una dirección de este tipo https://github.com/johannague/tutorial_wagtail_final/blob/3b5b24b3ef0c4221fca32c5cee961d2ed5074f9f/viajes/templates/viajes/viajes_page.html#L16  porque cuando lo despliegues en un servidor no va a funcionar. Corrígelo.

**Comment by johannague** [comment]
modificado los enlaces, de todo el proyecto.
